### ISSUE TITLE
Elm

### ISSUE THREAD

**Issue by cartoloupe** [webstackers/meetup#7]
[Elm](http://elm-lang.org/) is a statically typed functional programming language that compiles to runtime-error free Javascript.

- designed for building front-end web applications
- maintainability and usability boost productivity
- immutable values
- stateless functions
- type inference
- pattern matching
- automatic code formatting

I can do a short presentation on things I have done and learned about involving Elm, including walkthroughs of some sample web apps, and examples on how the compiler can help drive the refactoring process. I am not an expert.

**Comment by adrianboyko** [comment]
I've written a few thousand lines of Elm and would be interested in helping to evangelize the language at WebStackers. I don't do presentations but could be on hand to help answer questions from the audience.

**Comment by nqthqn** [comment]
I would love to present on Elm. I organize https://www.meetup.com/Elm-Eug

We have remote presenters frequently.

**Comment by lenards** [comment]
I'm in Tucson; I've be game to help. My daily job is writing Elm.

**Comment by julianpistorius** [comment]
@cartoloupe FYI there is a [#tucson channel](https://elmlang.slack.com/messages/CAZRUSP6Z/) on the Elm Slack now.

**Comment by cartoloupe** [comment]
Thanks all, the responses here are really exciting to see 👍 Looking forward to talking Elm with y'all!

**Comment by BusyRich** [comment]
Is there anyone local that would be willing to present?

**Comment by lenards** [comment]
@cartoloupe is local.

**Comment by cartoloupe** [comment]
I'd love to present! I've been working on some slides that will last around 15 minutes.

**Comment by BusyRich** [comment]
@cartoloupe Awesome. I think 30-40m would be perfect if you have more you want to share/talk about. Just drop me an email (rich@busyrich.com) with your real name (excuse me if we have meant IRL) and a description of what your presentation will entail. We can then get this up on meetup.com and start pimping it.

**Comment by lenards** [comment]
@cartoloupe - if you are less inclined to stress to 30+ minutes, I could to 10 to 15 minutes (or 20) framed as an experience report from my last 4 months writing Elm for work.

**Comment by cartoloupe** [comment]
@BusyRich I sent you an email 👍 

@lenards Thank you, I think that is a great idea. I would be very interested in hearing about experiences of Elm for work.

**Comment by BusyRich** [comment]
@lenards I have reviewed @cartoloupe's email and his presentation outline looks great. However, we both agree it would be great to have you do your expose afterward, regardless of the length. Lets plan on having you be second up after him. No presentation required or anything, but if you want to put together slides we will happily facilitate you.

**Comment by BusyRich** [comment]
We have a schedule conflict with @cartoloupe so we will be moving this topic to August. Same plan as outlined above.

**Comment by lenards** [comment]
August would work for me.

**Comment by lenards** [comment]
Thanks again for selecting this topic. Thanks to @cartoloupe for creating the idea here and for presenting.

If you're interested in Elm and live in Tucson, stop by the Elm Slack's `#tucson` channel and say "hi".

From the talk:

@cartoloupe's slides are here http://bit.ly/vasanth-2018-08-elm-webstack
and the Tic Tac Toe Ellie app he referenced is here: https://ellie-app.com/33qFbBFXztHa1

for my talk slides: https://bitly.com/lenards-2018-08-elm-slides
and learning resources: https://bitly.com/lenards-elm-2018-08

Also, I recreate the live coding example: https://ellie-app.com/3478SXg2FNwa1

It occurred to me today that this might be a bit of a more realistic example given the questions and comments from folks: https://ellie-app.com/347bw2VjHPta1
